export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ADD = 'ADD'
export const SUB = 'SUB'
export const STORE = 'STORE'
export const DELETE = 'DELETE'
export const DELETE_ITEM = 'DELETE_ITEM'