export const SIGN_UP_START = 'SIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'

export const SIGN_IN_START = 'SIGN_IN_START'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

export const LOGOUT = 'LOGOUT'

export const SET_USER_DATA = 'SET_USER_DATA'

export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT'
export const AUTH_INITIATE_SIGN_UP_START = 'AUTH_INITIATE_SIGN_UP_START'
export const AUTH_INITIATE_SIGN_IN_START = 'AUTH_INITIATE_SIGN_IN_START'
export const AUTH_INITIATE_SIGN_IN = 'AUTH_INITIATE_SIGN_IN'
export const AUTH_INITIATE_SIGN_UP = 'AUTH_INITIATE_SIGN_UP'
export const AUTH_INITIATE_CHECK_STATE = 'AUTH_INITIATE_CHECK_STATE'
export const AUTH_INITIATE_FETCH_USER = 'AUTH_INITIATE_FETCH_USER'