export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REM_INGREDIENT = 'REM_INGREDIENT'
export const CLEAR_ORDER = 'CLEAR_ORDER'
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'

export const BB_INITIATE_FETCH_INGREDIENTS = 'BB_INITIATE_FETCH_INGREDIENTS'