export const PURCHASE_INIT = 'PURCHASE_INIT'
export const PURCHASE_ORDER_START = 'PURCHASE_ORDER_START'
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS'
export const PURCHASE_ORDER_FAILED = 'PURCHASE_ORDER_FAILED'

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT'
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'

export const ORDER_INITIATE_FETCH_ORDERS = 'ORDER_INITIATE_FETCH_ORDERS'
export const ORDER_INITIATE_PURCHASE_ORDER = 'ORDER_INITIATE_PURCHASE_ORDER'
